### PR TITLE
Add nix flake

### PR DESCRIPTION
**Pull request by cgeorgii**
#### Motivation
Having a nix flake file enables `nix` users to quickly start hacking on the code by providing tooling such as `cabal-install`, `ghcid` and `haskell-language-server`. Getting a dev environment is as easy as running `nix develop`!

### CODE REVIEW

**Review by mboes — COMMENTED** [review]
A lot of boilerplate for a simple library. Wouldn't even know how to maintain it. Perhaps you could tell me more about what a flake.nix file is useful for?

**Comment by cgeorgii** [comment]
Sure! I edited the PR description to include my motivation, but in essence it's an easy way to provide a development environment for the package. That eases contribution and could also serve as a base for a CI setup.

**Comment by mboes** [comment]
Thanks for contribution, and the explanation. The Flakes boilerplate is significant for a tiny one-file library like this one. So I'm keen that it not become a long-term maintenance burden. So prompted by your contribution, I added Devenv support in mainline, which generates the Flakes boilerplate on the basis of a higher-level declarative description.

**Comment by cgeorgii** [comment]
Fair enough! Thanks for letting me know :)

**Pull request closed without merging**
